[package]
name = "XDUthesis-typst"
version = "0.3.4"
entrypoint = "lib.typ"
authors = ["OrangeX4"]
license = "MIT"
description = "西安电子科技大学硕士学位论文Typst模板"
repository = "https://github.com/CoderJackZhu/XDUthesis-Typst"
keywords = ["Xidian University", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "master-proposal.typ"
thumbnail = "thumbnail.png"