[package]
name = "XDUthesis-Typst"
version = "0.4.0"
entrypoint = "lib.typ"
authors = ["OrangeX4"]
license = "MIT"
description = "西安电子科技大学学位论文模板。"
repository = "https://github.com/CoderJackZhu/XDUthesis-Typst"
keywords = ["Xidian University", "thesis"]
categories = ["thesis"]
exclude = ["imgs"]
compiler = "0.13.0"

[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "thumbnail.png"